server:
  port: "8080"
  mode: "debug"  # 可选：debug, release

logging:
  level: "info"  # debug, info, warn, error
  output: "console,file"
  
jwt:
  secret: "your-secret-key-here" # 在生产环境中应该使用环境变量
  access_expiration: 15    # 15 minutes
  refresh_expiration: 7    # 7 days

storage:
  type: "local"  # local, oss, s3, cos, qiniu
  local:
    path: "./uploads"
    max_file_size: 10485760
    allowed_types:
      - ".pdf"
      - ".doc"
      - ".docx"
      - ".txt"
      - ".md"

  s3:
    region: "us-west-2"
    bucket: "your-bucket"
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    access_key_secret: "${AWS_ACCESS_KEY_SECRET}"
    base_path: "uploads"

  cos:
    region: "ap-beijing"
    bucket: "your-bucket"
    secret_id: "${COS_SECRET_ID}"
    secret_key: "${COS_SECRET_KEY}"
    base_path: "uploads"

  qiniu:
    access_key: "${QINIU_ACCESS_KEY}"
    secret_key: "${QINIU_SECRET_KEY}"
    bucket: "your-bucket"
    domain: "your-domain.com"
    base_path: "uploads"